### ISSUE TITLE
SPA - jak podejść do obsługi danych? 

### ISSUE THREAD

**Issue by withoutlogin** [meetjspl/torun#10]
Hej, podrzucam slajdy do tematu obsługi danych w aplikacjach typu Single Page. Na końcu dokumentu linki do dwóch fajnych prezentacji w temacie GraphQL'a.

Szymon

[prezentacja.pdf](https://github.com/meetjspl/torun/files/2083396/Szymon_Kumorek_meet.js_obsluga_danych.pdf)

**Comment by DzikowskiW** [comment]
Dzięki za prezentację i slajdy! 👍
