### ISSUE TITLE
What I learned creating my first Open Source library

### ISSUE THREAD

**Issue by maciejmyslinski** [meetjspl/torun#11]
Tę prezkę przedstawiłem już w Poznaniu [na chill.js](
https://web.facebook.com/events/1860612420656129/permalink/1868374533213251/) i przyjęła się świetnie, dlatego podbijam świat dalej 😉😉

**Pitch prezki:**

*PL*
Zawsze marzyłem o stworzeniu swojej własnej biblioteki Open-Source. Nigdy nie brakowało mi też wymówek: muszę zdobyć więcej doświadczenia, jest tyle innych pilnych obowiązków, są lepsi ode mnie. Poza tym wydawało się, że każdy istotny problem został już rozwiązany. Założę się, że jesteś choć trochę podobny do mnie.
Z mojej prezentacji dowiesz się:
* jak zauważyłem problem, który nie został jeszcze rozwiązany,
* jak wypracowałem rozwiązanie,
* czego nauczyłem się po drodze.

No i będziesz o krok bliżej stworzenia swojej własnej biblioteki Open-Source!

*EN*
I always dreamed about creating my own Open-Source library. I always had a lot of excuses, too: I'm not experienced yet, I don't have enough time, I don't have an idea. I bet you are a little bit like me.
From this presentation you'll learn:
* how I noticed a problem that wasn't yet solved
* what lead me to the solution
* what I learned along the way

And you may be one step closer to creating your own open-source project one day!

Chętnie wbiję w najbliższy wolny termin, jestem też deską ratunku w razie gdyby ktoś z prelegentów w ostatniej chwili nie mógł wystąpić 🙂

**Comment by maciejmyslinski** [comment]
Howdy @DzikowskiW, dzięki za dodanie tagu. Jak otwarty byłbyś, żebym prezentował ten temat w najbliższym terminie?

**Comment by maciejmyslinski** [comment]
@DzikowskiW organizowanie meetupów to pewnie niełatwe zadanie. Jak mogę pomóc?

**Comment by DzikowskiW** [comment]
Cześć Maciej! 

Dzięki za zgłoszenie, bardzo ciekawie wygląda Twój temat. Niestety toruński meet.js dopiero zaczyna się rozwijać i nie mamy póki co sponsorów. Przez to nie dysponujemy aktualnie budżetem, dzięki któremu moglibyśmy Ciebie zaprosić. 

Wierzę, że za jakiś czas uda nam się znaleźć firmę która zasponsorowałaby przyjazdy prelegentów spoza Torunia, wtedy postaramy się Ciebie zaprosić.

**Comment by maciejmyslinski** [comment]
@DzikowskiW dzięki za wgląd w to, co dzieje się od strony finansowej 💰

Gdybym pokrył koszty dojazdu i noclegu, czy odrzucisz moją propozycję?

**Comment by DzikowskiW** [comment]
@maciejmyslinski puść maila na torun@meetjs.pl dogadamy szczegóły mailowo

**Comment by maciejmyslinski** [comment]
@DzikowskiW bardzo dziękuję za zaproszenie! 🙇 
Niestety, środy są jedynymi dniami w tygodniu (oprócz weekendów), które mi nie pasują 😢 
Dogadajmy szczegóły mailowo 😉😉
