### ISSUE TITLE
[meet.js Toruń #2, 10.2018] VRT - czyli inny rodzaj testów

### ISSUE THREAD

**Issue by Anekses** [meetjspl/torun#4]
Świat nie kończy się na testach jednostkowych. Pokażę jak za pomocą kilkunastu obrazków zaoszczędzić dziesiątki godzin pracy developerów i testerów

**Comment by DzikowskiW** [comment]
@Anekses jest szansa, żebyś dodał slajdy z prezentacji jako komentarz do tego issue?
