### ISSUE TITLE
Typescript - dlaczego warto?

### ISSUE THREAD

**Issue by kazagkazag** [meetjspl/torun#9]
Typescript - dlaczego po roku pracy w TS uważam, że warto go używać w produkcyjnych projektach i dużych zespołach? Krótkie wprowadzenie w składnię, plusy, minusy i przykładowy kod.

**Comment by DzikowskiW** [comment]
Cześć Kamil! Wiem, że od czasu stworzenia tego issues'a trochę czasu minęło, mam nadzieję, że nadal chciałbyś przedstawić prezentację na meet.js Toruń :)

Czy w połowie marca lub w połowie maja chciałbyś opowiedzieć o Typescripcie bądź Jeście?

**Comment by kazagkazag** [comment]
Jasne, o jakim dokładnie marcowym terminie myślicie?

**Comment by DzikowskiW** [comment]
Wstępnie, wtorek 12 marca lub czwartek 14 marca jeśli będzie dostępna sala. Może przejdźmy na maila, to spokojnie się dogadamy (torun@meetjs.pl) :)
